"use client";
import Image from "next/image"; import {useEffect,useState} from "react";
const copy={en:{heroBody:"One point of contact. One coordinated process.",heroDetail:"We coordinate planning, design development, construction, renovation and built-in work through to a ready-to-use handover.",transformLead:"Attention in every step, toward a space that works beautifully for you.",servicesLead:"Integrated services for spaces that work in real life.",attentionLead:"The quality of a finished space begins with attention at every stage.",ctaBody:"New home, renovation or commercial space — we coordinate each stage to create a space that works for your needs and lifestyle."},th:{heroBody:"ออกแบบและรับเหมาก่อสร้างแบบครบวงจร",heroDetail:"ตั้งแต่การวางแนวคิด ออกแบบ ก่อสร้าง ตกแต่ง รวมถึงการควบคุมงานก่อสร้างและรีโนเวท ไปจนถึงการส่งมอบพื้นที่พร้อมใช้งาน",transformLead:"ใส่ใจในทุกขั้นตอน เพื่อพื้นที่ที่สมบูรณ์ในแบบของคุณ",servicesLead:"บริการครบวงจร เพื่อให้พื้นที่ที่ตอบโจทย์การใช้งานจริง",attentionLead:"ใส่ใจในรายละเอียดของงาน เพราะคุณภาพของพื้นที่ที่เสร็จสมบูรณ์ เริ่มจากความใส่ใจในทุกขั้นตอน",ctaBody:"บ้านใหม่ ปรับปรุงพื้นที่เดิม หรือพื้นที่สำหรับธุรกิจ เราพร้อมดูแลและประสานงานในทุกขั้นตอน เพื่อให้คุณได้พื้นที่ที่ตอบโจทย์การใช้งานและไลฟ์สไตล์"}};
const transform=[["UNDERSTAND","Space · Needs · Budget","เข้าใจพื้นที่ ความต้องการ และงบประมาณ","/images/transform-understand.jpg"],["PLAN & DESIGN","Planning · Design · Material","วางแผน ออกแบบ และเลือกวัสดุ","/images/transform-plan-design.jpg"],["BUILD","Renovation · Construction · Built-in","งานปรับปรุง ก่อสร้าง และ Built-in","/images/transform-build.jpg"],["COMPLETE","Installation · Review · Handover","ติดตั้ง ตรวจสอบ และส่งมอบ","/images/transform-complete.jpg"]];
const projects=[["RESIDENTIAL · NEW HOME","New Home","Interior & Built-in","/images/project-new-home.jpg","/projects/moden-rangsit-klong-4"],["RESIDENTIAL · RENOVATION","Home Renovation","Interior & Built-in","/images/project-renovation.jpg","/projects#home-renovation"],["COMMERCIAL","OFFICE / RETAIL SPACES","Renovation & Built-in","/images/project-commercial.png","/projects#commercial"]];
const services=[["Interior Design","ออกแบบและวางผังการใช้งานพื้นที่ให้ตอบโจทย์การใช้งานจริง และสะท้อนถึงสไตล์ ภาพลักษณ์ และความต้องการของเจ้าของโครงการหรือเจ้าของธุรกิจ เพื่อให้พื้นที่สามารถทำงานร่วมกับผู้ใช้งานได้อย่างมีประสิทธิภาพสูงสุด"],["Renovation & Construction","งานปรับปรุง ต่อเติม และรีโนเวทพื้นที่เดิมให้เหมาะกับการใช้งานใหม่ พร้อมประเมินสภาพพื้นที่และขอบเขตงาน เพื่อวางแผนงบประมาณให้สอดคล้องกับความต้องการ"],["Built-in Furniture","งานผลิตและติดตั้งเฟอร์นิเจอร์ Built-in ตามแบบและการใช้งานจริง โดยให้ความสำคัญกับรายละเอียด วัสดุ การผลิต และคุณภาพของงานติดตั้ง"],["M&E Services","บริการออกแบบ ติดตั้ง และบริหารระบบไฟฟ้า ระบบประปา ระบบปรับอากาศ และงานระบบที่เกี่ยวข้อง ให้เหมาะสมกับขนาดและรูปแบบของโครงการ พร้อมคำนึงถึงมาตรฐานความปลอดภัย"],["Project Management","ดูแลและประสานงานโครงการ ทั้งขอบเขตงาน งบประมาณ ระยะเวลา และคุณภาพ พร้อมติดตามและรายงานความคืบหน้า เพื่อให้เจ้าของโครงการเห็นภาพและสถานะของงานตลอดโครงการ"]];
function Icon({type}:{type:"facebook"|"line"|"phone"|"email"}){if(type==="phone")return <svg viewBox="0 0 24 24"><path d="M6.6 10.8c1.7 3.3 3.3 4.9 6.6 6.6l2.2-2.2c.3-.3.7-.4 1.1-.3 1.2.4 2.5.6 3.8.6.6 0 1 .4 1 1V20c0 .6-.4 1-1 1C10.8 21 3 13.2 3 3.7c0-.6.4-1 1-1h3.5c.6 0 1 .4 1 1 0 1.3.2 2.6.6 3.8.1.4 0 .8-.3 1.1l-2.2 2.2z"/></svg>; if(type==="email")return <svg viewBox="0 0 24 24"><path d="M3 5h18v14H3V5zm9 8L5 8v9h14V8l-7 5zm0-2 7-5H5l7 5z"/></svg>; if(type==="facebook")return <svg viewBox="0 0 24 24"><path d="M13.5 21v-8h2.7l.4-3h-3.1V8.1c0-.9.2-1.5 1.6-1.5h1.7V4c-.3 0-1.3-.1-2.5-.1-2.5 0-4.2 1.5-4.2 4.3V10H7.3v3h2.8v8h3.4z"/></svg>; return <span className="lineBadge">LINE</span>}
export default function Home(){
const[lang,setLang]=useState<"en"|"th">("th");
const t=copy[lang];

useEffect(()=>{
  const nodes = Array.from(document.querySelectorAll<HTMLElement>("[data-reveal]"));
  const observer = new IntersectionObserver((entries)=>{
    entries.forEach((entry)=>{
      if(entry.isIntersecting){
        (entry.target as HTMLElement).classList.add("is-visible");
        observer.unobserve(entry.target);
      }
    });
  },{threshold:0.12,rootMargin:"0px 0px -8% 0px"});
  nodes.forEach((node)=>observer.observe(node));
  return ()=>observer.disconnect();
},[]);

return <main><header className="siteHeader"><a className="brand" href="#top"><Image src="/logo/muck-logo.png" alt="MUCK Design" width={120} height={70} priority/></a><nav><a href="#projects">Projects</a><a href="#services">Services</a><a href="#process">How We Work</a><a href="#about">About</a><a href="#contact">Contact</a></nav><div className="headerActions"><button className="lang" onClick={()=>setLang(lang==="en"?"th":"en")}>{lang==="en"?"TH | EN":"EN | TH"}</button><a className="contactBtn" href="#contact">CONTACT US →</a></div></header>
<section className="hero" id="top"><div className="heroCopy reveal" data-reveal><p className="eyebrow">RESIDENTIAL & COMMERCIAL</p><h1>FROM SPACE<br/>TO LIVING.</h1><p className="serviceLine">Turnkey Services · Renovation · Built-in</p><p className="heroStrong">{t.heroBody}</p><p className="heroDetail">{t.heroDetail}</p><a className="solidBtn" href="/projects">EXPLORE PROJECTS</a></div><div className="heroImage"><Image className="heroPhoto" src="/images/hero-residential.jpg" alt="Completed MUCK Design residential project" width={2048} height={1177} quality={95} priority sizes="(max-width:900px) 100vw, 64vw"/><span className="tagline">The Path to Better Living</span></div></section>
<section className="section reveal" id="process" data-reveal><div className="sectionTitleRow"><h2>How We Transform Space <span>: Perfection in Every Step</span></h2><i/></div><p className="lead">{t.transformLead}</p><div className="transformGrid">{transform.map(([a,b,c,d])=><article className="motionCard" key={a}><div className="imageBox processImage"><Image src={d} alt={a} fill quality={95} sizes="(max-width:900px) 50vw, 25vw"/></div><h3>{a}</h3><p>{b}</p>{lang==="th"&&<p className="thai">{c}</p>}</article>)}</div></section>
<section className="section soft reveal" id="projects" data-reveal><div className="sectionTitleRow"><h2>Selected Projects</h2><i/><a href="/projects">VIEW ALL PROJECTS →</a></div><div className="projectGrid">{projects.map(([a,b,c,d,e])=><a className="projectCardLink" href={e} key={b}><article className="motionCard"><div className="imageBox projectImage"><Image src={d} alt={b} fill quality={95} sizes="(max-width:900px) 100vw, 33vw"/></div><p className="category">{a}</p><h3>{b}</h3><p>{c}</p><span className="viewProjectLink">VIEW PROJECT <span aria-hidden="true">→</span></span></article></a>)}</div></section>
<section className="section reveal" id="services" data-reveal><div className="sectionTitleRow"><h2>Our Services</h2><i/></div><p className="lead">{t.servicesLead}</p><div className="servicesLayout"><div className="serviceList">{services.map(([a,b])=><div className="serviceRow" key={a}><strong>{a}</strong><p>{lang==="th"?b:""}</p><span>→</span></div>)}</div><div className="turnkey"><Image src="/images/service-turnkey.png" alt="Turnkey services interior" fill quality={95} sizes="(max-width:900px) 100vw, 44vw"/><div className="turnkeyText"><h3>TURNKEY SERVICES</h3><p>One coordinated process across design, renovation, built-in, M&amp;E and project management.</p></div></div></div></section>
<section className="section soft reveal" id="about" data-reveal><div className="attentionHeader"><h2>Built With Attention</h2><p>{t.attentionLead}</p></div><div className="attentionGrid">{[["MATERIAL","การเลือกวัสดุ","/images/attention-material.jpg"],["CRAFTSMANSHIP","รายละเอียดงานและการผลิต","/images/attention-craftsmanship.png"],["ON SITE","การควบคุมและประสานงานหน้างาน","/images/attention-onsite.jpg"],["FINISHING","การตรวจสอบรายละเอียดก่อนส่งมอบ","/images/attention-finishing.jpg"]].map(([a,b,c])=><article className="motionCard" key={a}><div className="imageBox attentionImage"><Image src={c} alt={a} fill quality={95} sizes="(max-width:900px) 50vw, 25vw"/></div><h3>{a}</h3>{lang==="th"&&<p className="thai">{b}</p>}</article>)}</div></section>
<section className="cta reveal" id="contact" data-reveal><div className="ctaImage"><Image src="/images/cta-bedroom.png" alt="Completed MUCK Design bedroom" fill quality={95} sizes="(max-width:900px) 100vw, 50vw"/></div><div className="ctaCopy"><h2>LET’S CREATE<br/>A SPACE THAT WORKS FOR YOU</h2><p>{t.ctaBody}</p><a href="https://lin.ee/xMvkeiO" target="_blank" rel="noreferrer" className="solidBtn">TALK TO MUCK DESIGN</a><div className="contactStrip"><a href="https://lin.ee/xMvkeiO" target="_blank" rel="noreferrer"><Icon type="line"/><span>LINE</span></a><a href="tel:+66966289516"><Icon type="phone"/><span>096-6289-516</span></a><a href="tel:+66632179355"><Icon type="phone"/><span>063-2179-355</span></a><a href="mailto:muckdesignteam@gmail.com"><Icon type="email"/><span>Email</span></a></div></div></section>
<footer><div><span>Muck Design by BS&amp;P Beyond Home Design Co.,Ltd.</span><span>:</span><span>The Path to Better Living</span></div><div className="socials"><a href="https://www.facebook.com/61581893797548/" target="_blank" rel="noreferrer"><Icon type="facebook"/></a><a href="https://lin.ee/xMvkeiO" target="_blank" rel="noreferrer"><Icon type="line"/></a><a href="tel:+66966289516"><Icon type="phone"/></a><a href="mailto:muckdesignteam@gmail.com"><Icon type="email"/></a></div></footer></main>}
